# Generated by Django 2.2 on 2020-04-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('entry_image', models.ImageField(upload_to='entry/{self.entry_gate}')),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('entry_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='core.Gate')),
                ('exit_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='core.Gate')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
        ),
    ]
