# Generated by Django 2.2 on 2020-04-04 05:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='encoding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=0, null=True, size=1000),
        ),
        migrations.AlterField(
            model_name='log',
            name='entry_image',
            field=models.ImageField(null=True, upload_to='entry/{self.entry_gate}'),
        ),
        migrations.AlterField(
            model_name='log',
            name='exit_gate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit', to='core.Gate'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
